import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'TodoList (NextJS, Prisma, MongoDB)',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-slate-800 text-slate-100 ${inter.className}`}
      >
        <main className="max-w-lg p-8 m-auto">{children}</main>
      </body>
    </html>
  );
}

